export const params = {
    grid_selector: '[data-ca-block-manager-grid-id]',
    block_selector: '[data-ca-block-manager-snapping-id]',
    block_disabled_class: 'bm-block-manager__block--disabled',
    block_got_up_class: 'bm-block-manager__block--got-up',
    block_got_down_class: 'bm-block-manager__block--got-down',
    menu_selector: '[data-ca-block-manager-menu]',
    action_selector: '[data-ca-block-manager-action]',
    switch_selector: '[data-ca-block-manager-switch]',
    switch_icon_selector: '[data-ca-block-manager-switch-icon]',
    switch_icon_show_selector: '[data-ca-block-manager-switch-icon="show"]',
    switch_icon_hide_selector: '[data-ca-block-manager-switch-icon="hide"]',
    switch_icon_hidden_class: 'bm-block-manager__icon--hidden',
    move_selector: '[data-ca-block-manager-move]',
    sortable_items_selector: '> *:not(#litecheckout_form):not(#litecheckout_final_section)',
    _hover_element: {},
    _self: {},
};
