REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(0,  'NONE');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(1,  'DRAFT');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(2,  'CREATED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(3,  'ERROR');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(4,  'LOST');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(5,  'UNEXPECTED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(6,  'CANCELED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(7,  'SENDER_SENT');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(8,  'SENDER_WAIT_FULFILMENT');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(9,  'SENDER_WAIT_DELIVERY');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(10,  'FULFILMENT_LOADED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(11,  'FULFILMENT_ARRIVED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(12,  'FULFILMENT_PREPARED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(13,  'FULFILMENT_TRANSMITTED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(14,  'DELIVERY_LOADED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(15,  'DELIVERY_AT_START');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(16,  'DELIVERY_TRANSPORTATION');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(17,  'DELIVERY_ARRIVED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(18,  'DELIVERY_TRANSPORTATION_RECIPIENT');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(19,  'DELIVERY_ARRIVED_PICKUP_POINT');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(20,  'DELIVERY_DELIVERED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(21,  'RETURN_PREPARING');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(22,  'RETURN_ARRIVED_DELIVERY');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(23,  'RETURN_ARRIVED_FULFILMENT');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(24,  'RETURN_PREPARING_SENDER');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(25,  'RETURN_RETURNED');
REPLACE INTO ?:yd_statuses (yd_status_id, yd_status_code) VALUES(26,  'RETURN_TRANSMITTED_FULFILMENT');

REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(0,  'Без статуса', 'Обрабатывается', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(1,  'Черновик', 'Обрабатывается', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(2,  'Создан', 'Обрабатывается', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(3,  'Ошибка', 'Обрабатывается', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(4,  'Утерян', 'Утерян', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(5,  'Статус уточняется', 'Статус уточняется', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(6,  'Отменён', 'Отменен', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(7,  'Ждёт подтверждения службы доставки', 'Обрабатывается', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(8,  'Ожидается на едином складе', 'Обрабатывается', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(9,  'Ожидается в службе доставки', 'Обрабатывается', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(10,  'Подтверждён единым складом', 'Обрабатывается', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(11,  'На едином складе', 'Доставляется', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(12,  'Готов к передаче в службу доставки', 'Доставляется', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(13,  'Передан в службу доставки', 'Передан в службу доставки', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(14,  'Подтверждён службой доставки', 'Обрабатывается', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(15,  'На складе службы доставки', 'Доставляется', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(16,  'Доставляется', 'Доставляется', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(17,  'В городе покупателя', 'Доставляется', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(18,  'Доставляется по городу', 'Доставляется', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(19,  'В пункте самовывоза', 'В пункте самовывоза', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(20,  'Доставлен', 'Доставлен', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(21,  'Готовится к возврату', 'Возвращается в магазин', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(22,  'Возвращён на склад службы доставки', 'Возвращается в магазин', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(23,  'Возвращён на единый склад', 'Возвращается в магазин', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(24,  'Возвращается в магазин', 'Возвращается в магазин', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(25,  'Возвращён в магазин', 'Возвращён в магазин', 'ru');
REPLACE INTO ?:yd_status_descriptions (yd_status_id, yd_status_name, yd_status_info, `lang_code`) VALUES(26,  'Возвращается в магазин', 'Возвращается в магазин', 'ru');
